name: CI

on:
    push:
        branches: [ main ]
    pull_request:

permissions:
    contents: read

jobs:
    coding-style:
        name: Coding Style
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@v2
              with:
                  coverage: "none"
                  extensions: intl, ctype, iconv
                  php-version: 8.2
                  tools: composer

            - name: "Composer install"
              uses: ramsey/composer-install@v4
              with:
                  working-directory: "tools/php-cs-fixer"

            - name: "PHP-CS-Fixer"
              run: ./tools/bin/php-cs-fixer check