name: Diff spec

on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * MON'

jobs:
    check-spec:
        name: Check SDK is in sync with spec
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: composer update --no-interaction

            - name: Regenerate SDK library
              run: rm -rf generated && vendor/bin/jane-openapi generate --config-file=.jane-openapi.php

            - name: Rector
              run: vendor/bin/rector

            - name: Code style
              run: PHP_CS_FIXER_IGNORE_ENV=1 ./vendor/bin/php-cs-fixer fix

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v7